### ISSUE TITLE
Error when creating event location

### ISSUE THREAD

**Issue by y3kdaniel** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#15]
I am getting an error when trying to add a location to an event in CiviEvent, it is only happening since 4.7.18 update when I try to create the location using an address supplied when doing a postcode lookup. Before updating to 4.7.18 using an address from lookup worked correctly, so maybe this module needs an update to work with a change in 4.7.18 or a bug was introduced in 4.7.18, but to me it appears to be the former after the trial and error listed below.

I have found the issue lies within in the Country and State (County) being pre filled out before using the postcode lookup, if I remove them and re-add them after adding the address via lookup it works correctly.
If I create the event location by typing in the address manual then all works fine (to clarify that is with the country and county in its pre-filled state), and I can go back in to it using the postcode lookup to edit the location without error.

Too bad the PAF does not include county data any more or the country and county could have been added by the lookup, I suppose it could be possible to ditch using County in CiviCRM since it is no longer has a purpose in terms of postal services or finding an address but that is out of scope of this module.

The error: "One of parameters (value: ) is not of the type Integer"

The backtrace is:
`#0 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Error.php(374): CRM_Core_Error::backtrace()
#1 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Utils/Type.php(476): CRM_Core_Error::fatal("One of parameters  (value: ) is not of the type Integer")
#2 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/DAO.php(1374): CRM_Utils_Type::validate("", "Integer")
#3 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/DAO.php(1291): CRM_Core_DAO::composeQuery(" SELECT phone, ltype.name as locationType, ph.is_primary as is_primary,\n    ...", (Array:1), TRUE)
#4 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/BAO/Phone.php(219): CRM_Core_DAO::executeQuery(" SELECT phone, ltype.name as locationType, ph.is_primary as is_primary,\n    ...", (Array:1))
#5 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/BAO/Block.php(203): CRM_Core_BAO_Phone::allEntityPhones((Array:2))
#6 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/BAO/Block.php(247): CRM_Core_BAO_Block::getBlockIds("phone", NULL, (Array:2))
#7 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/BAO/Location.php(66): CRM_Core_BAO_Block::create("phone", (Array:14), "event")
#8 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Event/Form/ManageEvent/Location.php(263): CRM_Core_BAO_Location::create((Array:14), TRUE, "event")
#9 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Form.php(453): CRM_Event_Form_ManageEvent_Location->postProcess()
#10 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(169): CRM_Core_Form->mainProcess()
#11 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(136): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Event_Form_ManageEvent_Location), "upload")
#12 /REMOVED_PATH/public/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Event_Form_ManageEvent_Location), "upload")
#13 /REMOVED_PATH/public/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_ManageEvent_Location), "upload")
#14 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("upload")
#15 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(113): CRM_Core_Controller->run()
#16 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(283): CRM_Utils_Wrapper->run("CRM_Event_Form_ManageEvent_Location", "Event Location", (Array:0))
#17 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:14))
#18 /REMOVED_PATH/public/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:4))
#19 /REMOVED_PATH/public/sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke((Array:4))
#20 /REMOVED_PATH/public/includes/menu.inc(527): civicrm_invoke("event", "manage", "location")
#21 /REMOVED_PATH/public/index.php(21): menu_execute_active_handler()
#22 {main}`

**Comment by y3kdaniel** [comment]
Did some digging, the issue is that the javascript from this module sets the state_province_id value to '' but if it is empty CiviCRM is then throwing an error which it did not do in the past. Just to confuse things when it does this it doesn't trigger the form field to change what is shown so you don't notice that it has emptied the value.

So I submit a pull request (#16) to correct the javascript in this module so that it also empties the state name shown on the address form and I move to get the issue fixed on the CiviCRM side that is throwing the error on an empty state_province_id.
